version: '3.9'

services:
  mongo-swagger:
    image: mongo:4.4
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=swagger
      - MONGO_INITDB_USERNAME=swagger
      - MONGO_INITDB_PASSWORD=1234
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db:/data/db
volumes:
  data: